[package]
name = "mini-me"
version = "0.1.0"
authors = ["Avarel <avarelpm@gmail.com>"]
description = "A multiline console prompt for Rust."
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
mini_me = { path = "./lib" }
clap = "2.33"